[package]
name = "compreston-site"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.12.0"
axum = "0.6.0"
shuttle-axum = "0.12.0"
tokio = "1.26.0"
tower-http = {version = "0.4.0"}
tracing-subscriber = "0.3.16"